### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by mprymek** [svard/hello_phoenix#1]
Hello,

thank you very much for this example! Unfortunately it doesn't work for me. Compilation went ok, phoenix runs ok but in the browser I get `Uncaught Error: Cannot find module "web/static/js/app" from "/" at chat.js:10818` and nothing is rendered to html.

I've tried to fix it without success. Do you have any suggestion? Does it work for you as it is in this repo?

My setup: FreeBSD 10, Elixir 1.2.1, Elm 0.16.0

P.S. https://github.com/urfolomeus/seat_saver works for me so there's probably something wrong in the javascript/brunch part.

**Comment by svard** [comment]
It seems the issue is that the version of the phoenix client that is bundled in the elm-phoenix package is not compatible with the version of phoenix that is installed by mix. I have updated phoenix.js in the elm-phoenix package and the chat page loads successfully for me again.

**Comment by mprymek** [comment]
Works now, wonderful, thx!
